baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Portafolio Israel"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true


    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: ""
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Bienvenido(a)" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hola mi nombre es"
    title: "Israel"
    subtitle: "Desarrolador full stack"
    content: "Un apasionado desarrollador de aplicaciones web. Tiendo a utilizar tecnologías web modernas para crear sitios web que se vean geniales, siempre en constante desarrollo."
    image: /images/laragon.png
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/ISTEMEFA?tab=repositories
        - icon: fab fa-linkedin
          url: https://example.comhttps://www.linkedin.com/in/israel-mege-98a03014b/
     

  # About
  about:
    enable: true
    title: "Sobre mi"
    image: "/images/laragon.png"
    content: |-
      I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

      I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Tecnologías con las que he estado trabajando recientemente:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Java"
        - "Angular"
        - "Hugo"

  # Experience
  experience:
    enable: true
    title: "Experiencia"
    items:
      - job: "Soporte tecnico call center"
        company: "Entel call center"
        companyUrl: "https://www.entel.cl/"
        date: "24/06/2022 - 30/09/2022" 
        content: "Asistentencia a traves de la aplicaciones ServiceNow apoyadando en todo los servicios informaticos de supermecados SMU. "

      
  # Education
  education:
    enable: true
    title: "Educacion"
    index: false
    items:
      - title: "Ingenieria ejecucion industrial"
        school:
          name: "Universidad Catolica de la Santisima Concepcion"
          url: "https://it.ucsc.cl/carreras/ingenieria-de-ejecucion-industrial/"
        date: "2020 - 2023"
        content: |-
          Perfil de egreso
            - El Ingeniero de Ejecución Industrial, titulado de la Universidad Católica de la Santísima Concepción, es un profesional con competencias que le permiten formular, implementar, administrar, optimizar e innovar sistemas productivos de bienes y servicios.
      - title: "Desarrollador Java Full Stack"
        school:
          name: "Academia Desafios Latam"
          url: "https://desafiolatam.com/"
        date: "2022 - 2022 (480h)"
        content: |-
          Perfil de egreso
            -Construir proyectos full stack mezclando interfaces web construidas en el entorno de Java con framework
            como spring boot ademas desarrollar la capacidad de adaptacion de diferentes legnuajes segun el mercado laboral. 
        
      - title: "Tecnico en Automatizacion Industrial"
        school:
          name: "Universidad Catolica de la Santisima Concepcion"
          url: "https://it.ucsc.cl/carreras/tecnico-universitario-en-automatizacion-industrial/"
        date: "2017- 2019 "
        content: |-
          Perfil de egreso
            -Técnico con competencias específicas orientadas al montaje, operación y mantención de los sistemas automatizados industriales, desde la perspectiva de la confiabilidad, disponibilidad, calidad, seguridad y respeto medioambiental.
  
  # Achievements
 # achievements:
  #  enable: true
    # title: "Custom Name"
 #   items:
  #    - title: Google kickstart runner
   #     content: I solved all problems with optimal solution.
    #    url: https://example.com
     # - title: Facebook Hackathon Winner
      #  content: Developed a product using Artificial Intelligence.
      #- title: Hugo Profile
     #   content: Developed a theme and getting 1K+ downloads per month.
     #   url: "https://github.com/gurusabarish/hugo-profile"
     # - title: Microsoft Imagine Runner
     #   content: We are developed a product which can help others.
     # - title: Google Summer of Code
      #  content: Contributed to a open source project.
      #  url: https://example.com

  # projects
  projects:
    enable: true
    title: "Proyectos"
    items:
      - title: CRUD Angular
        content: CRUD que consume una Api para agregar usuarios con sus datos personales con validacion de informacion. 
        image: /images/projects/angular.png
        featured:
          name: Link proyecto
          link: https://github.com/ISTEMEFA/CRUD_Angular_Spring
        badges:
          - "Boostrap"
          - "Angular"
          - "Tipecript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          

      - title: Api Spring boot
        content: Api que interactua con una base de datos a traves de un CRUD Angular
        image: /images/projects/converter.jpg
        featured:
          name: Link Proyecto
          link: https://github.com/ISTEMEFA/CRUD-pringBotApi
        badges:
          - "Java"
          - "SpringBoot"
          - "SQL"
        links:
          - icon: fab fa-github
            url: https://github.com/ISTEMEFA/CRUD-pringBotApi

      

  #Contact
  contact:
    enable: true
    title: "Contactos"
    content: Enviame un
    email: israelmege@gmail.com
    btnName: Mi correo
  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Redes sociales
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
     

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
